"""
plugins_flags.py
------------

Plugin Managing Utility.
"""

import pathlib
import pkg_resources

from manim import console

__all__ = ["list_plugins", "update"]


def get_plugins():
    plugins = {
        entry_point.name: entry_point.load()
        for entry_point in pkg_resources.iter_entry_points("manim.plugins")
    }
    return plugins


def list_plugins():
    console.print("[green bold]Plugins:[/green bold]", justify="left")

    plugins = get_plugins()
    for plugin in plugins:
        console.print(f" • {plugin}")


def update():
    cfp = pathlib.Path(__file__).parent.parent.absolute()
    plugins_init = cfp / "plugins" / "__init__.py"
    with plugins_init.open("w") as f:
        f.write("# WARNING: THIS FILE IS AUTOGENERATED VIA `manim plugins -u`\n\n")

        plugins = get_plugins()
        for plugin in plugins:
            f.write(f"import {plugin}")

    console.print("[green bold]Update complete[/green bold]", justify="left")
