codecov:
  notify:
    require_ci_to_pass: no
    after_n_builds: 1
coverage:
  status:
    project:
      default:
        # Require 1% coverage, i.e., always succeed
        target: 1
    patch: true
    changes: false
comment: off
