version: 2
build:
  os: ubuntu-22.04
  apt_packages:
    - libpango1.0-dev
    - ffmpeg
python:
   version: 3.10
   install:
      - requirements: docs/rtd-requirements.txt
      - requirements: docs/requirements.txt
      - method: pip
        path: .
