version: 2
build:
  os: ubuntu-22.04

  tools:
    python: "3.10"

  apt_packages:
    - libpango1.0-dev
    - ffmpeg
    - graphviz
  
  jobs:
    pre_build:
      - export MANIM_SKIP_EXAMPLES=1

python:
   install:
      - requirements: docs/rtd-requirements.txt
      - requirements: docs/requirements.txt
      - method: pip
        path: .
