try:
    from dearpygui import dearpygui as dpg
except ImportError:
    pass

from manim import opengl as mgl
from manim.animation.animation import *
from manim.animation.changing import *
from manim.animation.composition import *
from manim.animation.creation import *
from manim.animation.fading import *
from manim.animation.growing import *
from manim.animation.indication import *
from manim.animation.movement import *
from manim.animation.numbers import *
from manim.animation.rotation import *
from manim.animation.specialized import *
from manim.animation.speedmodifier import *
from manim.animation.transform import *
from manim.animation.transform_matching_parts import *
from manim.camera.camera import *
from manim.camera.mapping_camera import *
from manim.camera.moving_camera import *
from manim.camera.multi_camera import *
from manim.camera.three_d_camera import *
from manim.gui.gui import *
from manim.mobject.frame import *
from manim.mobject.geometry.arc import *
from manim.mobject.geometry.boolean_ops import *
from manim.mobject.geometry.line import *
from manim.mobject.geometry.polygram import *
from manim.mobject.geometry.shape_matchers import *
from manim.mobject.geometry.tips import *
from manim.mobject.graph import *
from manim.mobject.graphing.coordinate_systems import *
from manim.mobject.graphing.functions import *
from manim.mobject.graphing.number_line import *
from manim.mobject.graphing.probability import *
from manim.mobject.graphing.scale import *
from manim.mobject.logo import *
from manim.mobject.matrix import *
from manim.mobject.mobject import *
from manim.mobject.opengl.dot_cloud import *
from manim.mobject.opengl.opengl_compatibility import *
from manim.mobject.opengl.opengl_geometry import *
from manim.mobject.opengl.opengl_image_mobject import *
from manim.mobject.opengl.opengl_mobject import *
from manim.mobject.opengl.opengl_point_cloud_mobject import *
from manim.mobject.opengl.opengl_surface import *
from manim.mobject.opengl.opengl_three_dimensions import *
from manim.mobject.opengl.opengl_vectorized_mobject import *
from manim.mobject.svg.brace import *
from manim.mobject.svg.svg_mobject import *
from manim.mobject.table import *
from manim.mobject.text.code_mobject import *
from manim.mobject.text.numbers import *
from manim.mobject.text.tex_mobject import *
from manim.mobject.text.text_mobject import *
from manim.mobject.three_d.polyhedra import *
from manim.mobject.three_d.three_d_utils import *
from manim.mobject.three_d.three_dimensions import *
from manim.mobject.types.image_mobject import *
from manim.mobject.types.point_cloud_mobject import *
from manim.mobject.types.vectorized_mobject import *
from manim.mobject.utils import *
from manim.mobject.value_tracker import *
from manim.mobject.vector_field import *
from manim.scene.moving_camera_scene import *
from manim.scene.scene import *
from manim.scene.scene_file_writer import *
from manim.scene.section import *
from manim.scene.three_d_scene import *
from manim.scene.vector_space_scene import *
from manim.scene.zoomed_scene import *
from manim.utils import rate_functions
from manim.utils.bezier import *
from manim.utils.color import *
from manim.utils.config_ops import *
from manim.utils.debug import *
from manim.utils.file_ops import *
from manim.utils.images import *
from manim.utils.iterables import *
from manim.utils.paths import *
from manim.utils.rate_functions import *
from manim.utils.simple_functions import *
from manim.utils.sounds import *
from manim.utils.space_ops import *
from manim.utils.tex import *
from manim.utils.tex_templates import *
from manim.utils.unit import *
