"""Manim's init subcommand.

Manim's init subcommand is accessed in the command-line interface via ``manim
init``. Here you can specify options, subcommands, and subgroups for the init
command.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import click
import cloup

from manim import config
from manim._config.utils import (
    CFG_DEFAULTS,
    get_template_names,
    select_resolution,
    update_cfg,
    copy_template_files,
)

from ..console import console

__all__ = ["select_resolution", "update_cfg", "project", "scene"]


def update_cfg(cfg_dict: dict[str, Any], project_cfg_path: Path) -> None:
    """Manages the creation of the manim.cfg file.

    Uses a dictionary generated by the user's preferences to create
    or update the manim.cfg file.

    Parameters
    ----------
    cfg_dict
        The dictionary containing the keys and values to be saved.

    project_cfg_path
        The path to the manim.cfg file.
    """
    config.read(project_cfg_path)
    for key, value in cfg_dict.items():
        config[key] = value
    with project_cfg_path.open("w") as conf:
        config.write(conf)


@cloup.argument("project_name", type=cloup.Path(path_type=Path), required=False)
@cloup.option(
    "-d",
    "--default",
    "default_settings",
    is_flag=True,
    help="Default settings for project creation.",
    nargs=1,
)
@cloup.option(
    "-f",
    "--force",
    is_flag=True,
    help="Initialize project even if folder already exists.",
)
def project(default_settings: bool, force: bool = False, **kwargs: Any) -> None:
    """Creates a new project.

    PROJECT_NAME is the name of the folder in which the new project will be initialized.
    """
    project_name: Path
    if kwargs["project_name"]:
        project_name = kwargs["project_name"]
    else:
        project_name = click.prompt("Project Name", type=Path)

    # in the future when implementing a full template system. Choices are going to be saved in some sort of config file for templates
    template_name = click.prompt(
        "Template",
        type=click.Choice(get_template_names(), False),
        default="Default",
    )

    new_cfg: dict[str, Any] = {}
    new_cfg_path = Path.resolve(project_name / "manim.cfg")

    if project_name.is_dir():
        if not force:
            console.print(
                f"\nFolder [red]{project_name}[/red] exists. Use --force to override.\n",
            )
            return
        else:
            console.print(
                f"\nFolder [yellow]{project_name}[/yellow] exists. Overwriting with --force...\n",
            )
    else:
        project_name.mkdir()

    if not default_settings:
        for key, value in CFG_DEFAULTS.items():
            if key == "scene_names":
                new_cfg[key] = template_name + "Template"
            elif key == "resolution":
                new_cfg[key] = select_resolution()
            else:
                new_cfg[key] = click.prompt(f"\n{key}", default=value)

        console.print("\n", new_cfg)
        if click.confirm("Do you want to continue?", default=True, abort=True):
            copy_template_files(project_name, template_name)
            update_cfg(new_cfg, new_cfg_path)
    else:
        copy_template_files(project_name, template_name)
        update_cfg(CFG_DEFAULTS, new_cfg_path)


@cloup.command(
    context_settings={"show_default": True, "ignore_unknown_options": True},
    no_args_is_help=True,
)
@cloup.argument("scene_name", type=str, required=True)
@cloup.argument("file_name", type=str, required=False)
def scene(scene_name: str, file_name: str | None = None) -> None:
    """Inserts a new scene into the current project.

    SCENE_NAME is the name of the new scene class.
    """
    if file_name is None:
        file_name = click.prompt("File name", type=str)

    file_path = Path(file_name)
    if not file_path.is_file():
        console.print(f"\nFile [red]{file_name}[/red] does not exist.\n")
        return

    with file_path.open("a") as f:
        f.write(f"\n\nclass {scene_name}(Scene):\n    def construct(self):\n        pass\n")

    console.print(f"\n[green]Added scene {scene_name} to {file_name}[/green]")
