# Small script to extract the setup.py file generated by poetry build to the manim directory
# which will allow for editable installs.

from pathlib import Path
import os
from shutil import rmtree
from subprocess import run
import tarfile
from sys import argv

manimpath = Path(__file__).parent.parent

os.chdir(manimpath)

buildcomm = run(["poetry", "build"])

tarname = [f for f in os.listdir(manimpath / "dist") if f.endswith("." + "tar.gz")][-1]

tar = tarfile.open(name=manimpath / "dist" / tarname)

print(f"Found tarfile at {manimpath/'dist'/tarname}. Extracting setup.py.")

with open("setup.py", "wb") as setupfile:
    setupfile.write(tar.extractfile(tarname[:-7] + os.sep + "setup.py").read())

if not "--keep_dist" in argv:
    print("Removing dist folder since --keep_dist not supplied.")
    rmtree("dist")

print("Done. You can now install manim via setup.py.")
