name: black
on:
  workflow_dispatch:

jobs:
  format:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install black
        run: pip install black

      - name: Black
        run: |
          black manim tests example_scenes
      - name: Check for modified files
        shell: bash
        id: git-check
        run: |
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
          git ls-files -m>/d/diffmod.txt
      - name: Print Black Version if Failed
        shell: bash
        if: steps.git-check.outputs.modified == 'true'
        run: |
          blackVer=$(black --version)
          blackVersion=$(python -c "print('${blackVer}'.split()[2])")
          date=$(python -c "import time;print(time.localtime().tm_mday)")
          pushBranch="black-${blackVersion}-${date}"
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -B "$pushBranch"
          git add .
          git commit -m "Running Black On Master"
      - name: Push branch
        if: steps.git-check.outputs.modified == 'true'
        shell: bash
        run: |
          blackVer=$(black --version)
          blackVersion=$(python -c "print('${blackVer}'.split()[2])")
          date=$(python -c "import time;print(time.localtime().tm_mday)")
          pushBranch="black-${blackVersion}-${date}"
          git push -u origin "${pushBranch}" --force
      - name: Make a PR
        if: steps.git-check.outputs.modified == 'true'
        env:
          access_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $blackVer = black --version
          $blackVersion = python -c "print('$($blackVer)'.split()[2])"
          $date = python -c "import time;print(time.localtime().tm_mday)"
          $pushBranch="black-$($blackVersion)-$($date)"
          $filechange=(gc "D:/diffmod.txt").split() -join "`n`n"
          $postContents = @{title="Automated PR: Autoformat with black";
          head="manimcommunity:$($pushBranch)";
          base="master";
          body="This an automated pull request. Files Changed are `n `n ```````n$($filechange)`n``````"
          } | ConvertTo-Json -Compress
          echo "$postContents"
          Invoke-WebRequest `
            -Method POST `
            -Headers @{ "Accept" = "application/vnd.github.v3+json"; "Authorization"= "token $($env:access_token)"}`
            -Uri https://api.github.com/repos/manimcommunity/manim/pulls `
            -Body "$($postContents)"
