name: code coverage
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Poetry
        run: |
          pip install wheel
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

      - name: Get pip cache dir
        shell: bash
        id: pip-cache-and-time
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
          echo "::set-output name=date::$(/bin/date -u "+%m%Y")"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache-and-time.outputs.dir }}
          key: Linux-pip-${{ hashFiles('**/requirements.txt') }}-3.7-${{ steps.pip-cache-and-time.outputs.date }}

      - name: Install system dependencies (Linux)
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          sudo apt-get -y install libpango1.0-dev texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science texlive-fonts-extra tipa
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install manim
        run: |
          poetry install -E webgl_renderer

      - name: Create coverage report
        run: |
          poetry run coverage run -m pytest
          poetry run coverage run --append -m pytest --doctest-modules manim

      - name: Upload coverage
        uses: codecov/codecov-action@v1


